name: CI

on: 
  push:
    paths-ignore:
      - 'README.md'

jobs:
  build:
    runs-on: [windows-latest]
    steps:
        
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET 10 SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '10.0.x'
        
      - name: NuGet Restore
        run: dotnet restore Pinger.sln
                           
      - name: Build
        run: dotnet build Pinger.sln
           
      - name: Run Tests
        run: dotnet test -v n Pinger.sln
